---

- name: install prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
  become: yes

- name: add apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: add repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}-prod {{ ansible_distribution_release | lower }} main"
    state: present
  become: yes

- name: install dotnet
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dotnet-sdk-2.0.0
    - dotnet-dev-1.0.4
    - dotnet-dev-1.1.4
    - dotnet-hostfxr-1.0.1
    - dotnet-hostfxr-1.1.0
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
    - dotnet-sharedframework-microsoft.netcore.app-1.0.7
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
    - dotnet-sharedframework-microsoft.netcore.app-1.1.4
  become: yes
