---

- name: get dotnet version
  command: dotnet --info
  register: dotnetcore_current
  ignore_errors: yes

- include: install.yml
  when: dotnetcore_current.rc != 0 or not dotnetcore_current.stdout | search(dotnetcore_version_string_match)

- include: configure.yml
