---

# see: https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
# see: https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.0.md
- name: install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libunwind8-dev
    - gettext
    - libicu-dev
    - liblttng-ust-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - uuid-dev
    - unzip
    - zlib1g
  become: yes

- name: get dotnet version
  command: dotnet --info
  register: dotnetcore_current
  ignore_errors: yes

- debug:
    var: dotnetcore_current

- include: install.yml
  when: dotnetcore_current.rc != 0 or not dotnetcore_current.stdout | search(dotnetcore_version_string_match)

- include: configure.yml
